version: "3"
services:
  dockercomposemongodb:
    image: mongo:latest
    container_name: "dockercomposemongodb"
    ports:
      - 27017:27017
  springboot-mongo-docker:
    image: springboot-mongo-docker:1.0
    container_name: springboot-mongodocker
    ports:
      - 8080:8080
    links:
      - dockercomposemongodb
